trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureContainerRegistrySC: eng-lab-acr
  repositoryUrl: "891612567594.dkr.ecr.us-east-1.amazonaws.com/webapi"
  imageName: webapi
  tagName: $(Build.BuildId)
  kubernetesNamespace: default
  containerSC: aws-ecr-connection

stages:
- stage: BuildAndPush
  displayName: "Build and Push Docker Image"
  jobs:
  - job: Build
    displayName: "Build and Push Docker Image to ACR"
    steps:
    - checkout: self

    - task: Docker@2
      displayName: "Build and Push Docker Image"
      inputs:
        containerRegistry: "$(containerSC)"
        repository: $(repositoryUrl)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tagName)

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'helloapp'
        publishLocation: 'Container'



